### PR TITLE
Avoid using Duration.INFINITE

### LINKED ISSUE #188: [BUG] Crash with Kotlin 1.4-M3
**Describe the bug**
After update Kotlin version from 1.3.72 to 1.4-M3 I get the application crash at startup with the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.test.android.app.staging, PID: 14322
    java.lang.NoSuchMethodError: No virtual method getINFINITE()D in class Lkotlin/time/Duration$Companion; or its super classes (declaration of 'kotlin.time.Duration$Companion' appears in /data/app/ru.test.android.app.staging-axaBHv67rAt451NQ51DY5Q==/base.apk!classes3.dex)
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:70)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:24)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:90)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:75)
```

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 8
 - OS: Android 10
 - Store Version: 4.0.0-alpha06

### PR DESCRIPTION
**Pull request by chrisbanes**
It currently breaks consumers compiling with Kotlin 1.4-M3 (not sure why).

Added some TODOs to revert back to using Duration.INFINITE
once Store is compiled with Kotlin 1.4

Closes #188

### CODE REVIEW

**Comment by chrisbanes** [comment]
This works for me in https://github.com/chrisbanes/tivi/ 🎉

**Comment by eyalgu** [comment]
ty!
