### ISSUE TITLE
[BUG] Experimental Duration usage causes problem with Kotlin 1.6

### ISSUE THREAD

**Issue by kozaxinan** [dropbox/Store#331]
**Describe the bug**

Store uses toDuration method which doesn't exist anymore.

**To Reproduce**
Compile app with Kotlin 1.6.0-RC and store will throw exception.

```
   java.lang.NoSuchMethodError: No static method toDuration(DLjava/util/concurrent/TimeUnit;)J in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/~~IRSXWQfX07qm58ody-twgg==/de.is24.android.debug-iVN1VrbvGOFR0iQJz1pxVg==/base.apk!classes35.dex)
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:116)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:23)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:86)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:65)
```

**Expected behavior**

Store should work with Kotlin 1.6.0-RC

**Comment by digitalbuddha** [comment]
Hello could you kindly try this version
https://search.maven.org/artifact/com.dropbox.mobile.store/store4/4.0.2-KT15/jar 
it should work with kotlin 1.5+
