### ISSUE TITLE
[BUG] Crash in Store 4.0 with Kotlin 1.5.0-RC

### ISSUE THREAD

**Issue by SteinerOk** [dropbox/Store#263]
**Describe the bug**
Application crash after update Kotlin from 1.4.32 to 1.5.0-RC, no other changes in code.

Catch Exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.superapplication.android.app.debug, PID: 18674
    java.lang.NoSuchMethodError: No static method getHours(I)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/~~l_eMNOPYSnv8XUlDP7ycgA==/ru.superapplication.android.app.debug-ziiU-phO368T6tA7R1CseQ==/base.apk!classes33.dex)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:15)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)
```

**Comment by digitalbuddha** [comment]
Thanks will take a look tomorrow

**Comment by Uorlak** [comment]
Have the same issue, waiting for fix.

**Comment by jeffdcamp** [comment]
FYI... Because of this issue anyone that is using Compose may be busted.... Compose needs to use Android Studio Arctic Fox... Arctic Fox forces the use of the Kotlin 1.5.0-RC plugin... 

Store 4.0 is the only library we have that does not work with Kotlin 1.5

Thanks for looking into this!

**Comment by SteinerOk** [comment]
@digitalbuddha I think this crash related with https://blog.jetbrains.com/kotlin/2021/04/kotlin-1-5-0-rc-released/#duration-api-changes

**Comment by digitalbuddha** [comment]
Yup makes sense. I will have a fix up this week. I was contemplating
dropping duration as dependency all together

**Comment by digitalbuddha** [comment]
Hi friends, we won't be able to release until next week. We are working on fixing the codecov vulnerability prior to triggering any more releases.

**Comment by bishiboosh** [comment]
@digitalbuddha with the release of 1.5.0 today, do you think you'd be able to release a version so we can migrate safely ?

**Comment by digitalbuddha** [comment]
https://search.maven.org/artifact/com.dropbox.mobile.store/store4/4.0.1/jar

**Comment by bishiboosh** [comment]
I still seem to have the same issue, any idea why ? I have this crash :
```
java.lang.NoSuchMethodError: No static method toDuration(ILjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/com.enki.Enki750g-cJ-mwUBphcam5o5DgtJjRg==/base.apk!classes19.dex)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:16)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)
```

**Comment by SteinerOk** [comment]
@digitalbuddha I have the same issue with Kotlin 1.5.0 like described @bishiboosh.
I think it related with Duration-type variable, in Kotlin 1.4 rawValue after compile is Double, but in 1.5 it is Long. 
Store compiled with 1.4.10 and when try to use Store with Kotlin 1.5 we have crash (type incompatible).
My opinion, the 2 way to solve this problem:
1) compile Store with Kotlin 1.5, but we will have crash when use Store with Kotlin 1.4
2) remove usage Duration-type.

**Comment by bishiboosh** [comment]
@digitalbuddha I think removing Duration completely from the lib would be too much of an API change, I'd go with compiling Store with Kotlin 1.5 (and making it a breaking change like you first thought in #265)

**Comment by digitalbuddha** [comment]
Ah boo I misunderstood scope of the issue. Seems like we will need to support two versions

**Comment by digitalbuddha** [comment]
There doesn't seem to be a way to support both 1.4 and 1.5. I am going to generate a snapshot tomorrow morning...
Store4k15:4.0.0-Snapshot (will figure out how to name properly). 

We will then carry both versions until we can upgrade to kotlin 1.5 internally. We are currently blocked by a few third party sdks. 

Thank you all for the patience, this was a learning experience for me to not leak experimental apis.

**Comment by digitalbuddha** [comment]
Hi friends, once we merge https://github.com/dropbox/Store/pull/273 we will have a new snapshot: 4.0.2-KT15-SNAPSHOT 
This version should be compatible with kotlin 1.5. I expect to have the snapshot out by end of day (EST)

**Comment by digitalbuddha** [comment]
Yup. It auto closed. Good callout. Snapshot is deployed

**Comment by digitalbuddha** [comment]
folks try the snapshot? If it works fine I can start working on release

**Comment by bishiboosh** [comment]
@digitalbuddha I've tried it quickly before going on holidays and it seemed to work

**Comment by bishiboosh** [comment]
I'd wait on @SteinerOk to confirm because the amount of verification on my side is probably not enough (but I can attest it compiles fine however)

**Comment by jeffdcamp** [comment]
Where is your snapshot repository?

Version "4.0.2-KT15-SNAPSHOT" is not on Maven Central
https://search.maven.org/artifact/com.dropbox.mobile.store/store4

(what should I put in my gradle "repositories" section? )

**Comment by bishiboosh** [comment]
@jeffdcamp it's on sonatype snapshots

**Comment by SteinerOk** [comment]
@digitalbuddha I tested snapshot and work fine

@jeffdcamp use this repository         
`maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }`

**Comment by jeffdcamp** [comment]
@digitalbuddha Version "4.0.2-KT15-SNAPSHOT" works GREAT with our app and Kotlin 1.5.0!

**Comment by digitalbuddha** [comment]
Thanks folks. I will do the release tomorrow (famous last words)

**Comment by SteinerOk** [comment]
@digitalbuddha, You forgot about the release? :)

**Comment by digitalbuddha** [comment]
Got wrapped up will do today.

**Comment by user-fal** [comment]
The snapshot works also with Kotlin 1.4.31

**Comment by JvmName** [comment]
@digitalbuddha I don't see this on Maven, did the release go okay? https://repo1.maven.org/maven2/com/dropbox/mobile/store/store4/

**Comment by digitalbuddha** [comment]
Just went live. https://repo1.maven.org/maven2/com/dropbox/mobile/store/store4/4.0.2-KT15/

**Comment by JvmName** [comment]
I guess I was too eager -- thanks for shipping the release!
