### ISSUE TITLE
[BUG] Crash with Kotlin 1.4-M3

### ISSUE THREAD

**Issue by SteinerOkay** [dropbox/Store#188]
**Describe the bug**
After update Kotlin version from 1.3.72 to 1.4-M3 I get the application crash at startup with the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.test.android.app.staging, PID: 14322
    java.lang.NoSuchMethodError: No virtual method getINFINITE()D in class Lkotlin/time/Duration$Companion; or its super classes (declaration of 'kotlin.time.Duration$Companion' appears in /data/app/ru.test.android.app.staging-axaBHv67rAt451NQ51DY5Q==/base.apk!classes3.dex)
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:70)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:24)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:90)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:75)
```

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 8
 - OS: Android 10
 - Store Version: 4.0.0-alpha06

**Comment by digitalbuddha** [comment]
Thank you for reporting. I'll take a look at how to fix. Maybe we just need to go to 1.4

**Comment by chrisbanes** [comment]
I'm also hitting this 😢 . Although I can't work out _why_ it's happen, I can see `Duration.INFINITE` in the Kotlin 1.4-M3 source
