### PR TITLE
Remove deprecated code to fix error when users upgrade to kotlin 1.5 

### LINKED ISSUE #263: [BUG] Crash in Store 4.0 with Kotlin 1.5.0-RC
**Describe the bug**
Application crash after update Kotlin from 1.4.32 to 1.5.0-RC, no other changes in code.

Catch Exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.superapplication.android.app.debug, PID: 18674
    java.lang.NoSuchMethodError: No static method getHours(I)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/~~l_eMNOPYSnv8XUlDP7ycgA==/ru.superapplication.android.app.debug-ziiU-phO368T6tA7R1CseQ==/base.apk!classes33.dex)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:15)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:91)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:76)
```

### PR DESCRIPTION
**Pull request by digitalbuddha**
Fixes #263 
Unfortunately this is a breaking change. We need to release a new major version. I'll change to store5:5.0 after merge unless someone has a better idea

### CODE REVIEW

**Review by yigit — DISMISSED** [review]
why is this a breaking change? seems like you only changed internal code and no public API?
is that breaking because we'll pusht he user's kotlin dependency to 1.5.0 ?

**Comment by digitalbuddha** [comment]
Yeah so 1.4 doesn't work with new api we use. 1.5 doesn't work with current. I think I can just rewrite the helper function and avoid whole mess

**Comment by digitalbuddha** [comment]
@yigit all set, no need to have a breaking change.

**Review by yigit — APPROVED** [review]
thanks!

**Review by changusmc — APPROVED** [review]
